---
title: "College Majors & Incomes"
author: "Alexis Colangelo"
date: "12/18/2019"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(scales)
```

Read in dataset
```{r}
recent_grads = read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-10-16/recent-grads.csv") 
```

### What categories of majors make more money than others?

Distribution of median income
```{r}
recent_grads %>%
  ggplot(aes(Median)) +
  geom_histogram()
```

Major category looks like it explains a lot of the variation
```{r}
recent_grads %>%
  mutate(Major_category = fct_reorder(Major_category, Median)) %>%
  ggplot(aes(Major_category, Median)) +
  geom_boxplot() +
  scale_y_continuous(labels = dollar_format()) +
  coord_flip()
```


```{r}
recent_grads %>%
    mutate(Major_category = fct_reorder(Major_category, Median)) %>%
  group_by(Major_category) %>%
  summarize(Median = median(Median)) %>%
  ggplot(
    aes(Major_category, Median)) +
  geom_col() +
  scale_y_continuous(labels = dollar_format()) +
  coord_flip()
```

### What are the highest earning majors?

```{r}
majors_processed =
  recent_grads %>%
  arrange(desc(Median)) %>%
  select(Major, Major_category, Median, P25th, P75th) %>%
   mutate(Major = str_to_title(Major),
     Major = fct_reorder(Major, Median))
  
majors_processed %>%
  head(20) %>%
  ggplot(aes(Major, Median, color = Major_category)) +
  geom_point() +
  geom_errorbar(aes(ymin = P25th, ymax = P75th)) +
  expand_limits(y = 0) +
  coord_flip()
```

```{r}
majors_processed =
  recent_grads %>%
  arrange(desc(Median)) %>%
  select(Major, Major_category, Median, P25th, P75th, Sample_size) %>%
   mutate(Major = str_to_title(Major),
     Major = fct_reorder(Major, Median))


majors_processed %>%
  ggplot(aes(Sample_size, Median)) +
  geom_point() +
  geom_text(aes(label = Major), check_overlap = TRUE, vjust = 1, hjust = 1) +
  scale_x_log10()

majors_processed %>%
  filter(Sample_size >= 100) %>%
  head(20) %>%
  ggplot(aes(Major, Median, color = Major_category)) +
  geom_point() +
  geom_errorbar(aes(ymin = P25th, ymax = P75th)) +
  expand_limits(y = 0) +
  scale_y_continuous(labels = dollar_format()) +
  coord_flip() +
  labs(title = "What are the highest-earning majors?",
       subtitle = "Top 20 majors with at least 100 graduates surveyed. Bars represent the 25th to 75th percentile.",
      x = "",
      y = "Median salary of graduates")
  
```

### What are the lowest earning majors?

```{r}
majors_processed %>%
  tail(20) %>%
  ggplot(aes(Major, Median, color = Major_category)) +
  geom_point() +
  geom_errorbar(aes(ymin = P25th, ymax = P75th)) +
  expand_limits(y = 0) +
  coord_flip()
```



```{r}

```











